#!/usr/bin/env python3
"""Coach the deterministic worker without changing evaluation or scoring."""

from __future__ import annotations

import argparse
import json
import os
import tempfile
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from autoresearch.attempts import CATEGORY_DIRECTIONS, Attempt, read_attempts


UTC = timezone.utc
HERE = Path(__file__).resolve().parent


@dataclass(frozen=True)
class CoachResult:
    ran: bool
    changed: bool
    attempt_count: int
    category_counts: dict[str, int]
    categories_with_improvements: dict[str, int]
    categories_without_improvements: dict[str, int]
    untried_categories: list[str]
    last_ten_improved: bool
    playbook_priorities: list[str]
    do_not_try: list[str]
    explanation: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _write_text_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def _write_json_atomic(path: Path, value: dict[str, Any]) -> None:
    _write_text_atomic(
        path,
        json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n",
    )


def load_state(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"schema_version": 1, "last_coached_attempt_count": 0}
    state = json.loads(path.read_text(encoding="utf-8"))
    if state.get("schema_version") != 1:
        raise ValueError("Unsupported coach state schema")
    return state


def playbook_guidance(path: Path) -> tuple[list[str], set[str]]:
    if not path.exists():
        return list(CATEGORY_DIRECTIONS)[:3], set()
    section = ""
    priorities: list[str] = []
    blocked: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line == "## Explore next":
            section = "explore"
            continue
        if line == "## Do not try":
            section = "blocked"
            continue
        if line.startswith("## "):
            section = ""
            continue
        if not line.startswith("- ") or line == "- None.":
            continue
        category = line[2:].split(":", 1)[0].strip()
        if category not in CATEGORY_DIRECTIONS:
            continue
        if section == "explore" and category not in priorities:
            priorities.append(category)
        elif section == "blocked":
            blocked.add(category)
    return priorities, blocked


def _category_statistics(
    attempts: list[Attempt],
) -> tuple[Counter[str], Counter[str]]:
    counts: Counter[str] = Counter()
    improvements: Counter[str] = Counter()
    for attempt in attempts:
        for category in attempt.category.split("+"):
            if category not in CATEGORY_DIRECTIONS:
                continue
            counts[category] += 1
            if attempt.kept:
                improvements[category] += 1
    return counts, improvements


def _render_playbook(
    *,
    attempt_count: int,
    priorities: list[str],
    blocked: list[str],
    counts: Counter[str],
    flatlined: bool,
) -> str:
    lines = [
        "# Wickless autoresearch playbook",
        "",
        "Generated by the coach from the append-only attempt history.",
        "",
        "## Current diagnosis",
        f"- Attempts reviewed: {attempt_count}.",
        (
            "- The last 10 attempts produced no kept improvement."
            if flatlined
            else "- The recent search is still producing kept improvements."
        ),
        "",
        "## Explore next",
    ]
    if priorities:
        lines.extend(
            f"- {category}: {CATEGORY_DIRECTIONS[category]}"
            for category in priorities
        )
    else:
        lines.append("- None: every available category is currently exhausted.")
    lines.extend(("", "## Do not try"))
    if blocked:
        lines.extend(
            f"- {category}: {counts[category]} attempts and zero kept improvements."
            for category in blocked
        )
    else:
        lines.append("- None.")
    lines.extend(
        (
            "",
            "## Fixed rules",
            "- Never change the evaluator, policy, objective order, or acceptance gates.",
            "- Keep risk, execution, cost, and one-position safeguards immutable.",
            "- Test one coherent idea before combining categories.",
            "- Read attempts.log before selecting the next untried candidate.",
            "- Record every result; never erase discarded work.",
        )
    )
    if len(lines) > 40:
        raise RuntimeError("Generated playbook exceeds 40 lines")
    return "\n".join(lines) + "\n"


def run_coach_if_due(
    *,
    attempts_path: Path,
    playbook_path: Path,
    state_path: Path,
    interval: int = 20,
    force: bool = False,
) -> CoachResult:
    if not 15 <= interval <= 25:
        raise ValueError("coach interval must be between 15 and 25 attempts")
    attempts = read_attempts(attempts_path)
    worker_attempts = [row for row in attempts if row.category != "baseline"]
    state = load_state(state_path)
    last_coached = int(state.get("last_coached_attempt_count", 0))
    if len(worker_attempts) < last_coached:
        raise ValueError("attempts.log appears to have been truncated")
    due = force or len(worker_attempts) - last_coached >= interval
    counts, improvements = _category_statistics(worker_attempts)
    untried = [name for name in CATEGORY_DIRECTIONS if counts[name] == 0]
    existing_priorities, existing_blocked = playbook_guidance(playbook_path)
    if not due:
        return CoachResult(
            ran=False,
            changed=False,
            attempt_count=len(worker_attempts),
            category_counts=dict(counts),
            categories_with_improvements=dict(improvements),
            categories_without_improvements={
                name: count
                for name, count in counts.items()
                if count >= 5 and improvements[name] == 0
            },
            untried_categories=untried,
            last_ten_improved=any(row.kept for row in worker_attempts[-10:]),
            playbook_priorities=existing_priorities,
            do_not_try=sorted(existing_blocked),
            explanation="The coach interval has not been reached. The playbook was left unchanged.",
        )

    recent_improved = any(row.kept for row in worker_attempts[-10:])
    changed = False
    priorities = existing_priorities
    blocked = set(existing_blocked)
    if recent_improved:
        explanation = (
            "The recent search is still producing kept improvements, so the playbook was left unchanged. "
            f"The coach advanced its checkpoint after reviewing {len(worker_attempts)} attempts."
        )
    else:
        blocked = {
            name
            for name in existing_blocked
            if counts[name] >= 5 and improvements[name] == 0
        }
        exhausted = {
            name
            for name in CATEGORY_DIRECTIONS
            if counts[name] >= 5 and improvements[name] == 0
        }
        blocked.update(exhausted)
        available = [name for name in CATEGORY_DIRECTIONS if name not in blocked]
        available.sort(key=lambda name: (counts[name] != 0, counts[name], name))
        priorities = available[:3]
        rendered = _render_playbook(
            attempt_count=len(worker_attempts),
            priorities=priorities,
            blocked=sorted(blocked),
            counts=counts,
            flatlined=True,
        )
        current = playbook_path.read_text(encoding="utf-8") if playbook_path.exists() else ""
        changed = rendered != current
        if changed:
            _write_text_atomic(playbook_path, rendered)
        named = ", ".join(priorities) if priorities else "no remaining category"
        explanation = (
            "The last 10 attempts produced no kept improvement, so exhausted categories were moved to Do not try. "
            f"The playbook now prioritizes {named} as materially different search directions."
        )

    _write_json_atomic(
        state_path,
        {
            "schema_version": 1,
            "last_coached_attempt_count": len(worker_attempts),
            "last_run_at_utc": datetime.now(UTC).replace(microsecond=0).isoformat(),
            "playbook_changed": changed,
        },
    )
    return CoachResult(
        ran=True,
        changed=changed,
        attempt_count=len(worker_attempts),
        category_counts=dict(counts),
        categories_with_improvements=dict(improvements),
        categories_without_improvements={
            name: count
            for name, count in counts.items()
            if count >= 5 and improvements[name] == 0
        },
        untried_categories=untried,
        last_ten_improved=recent_improved,
        playbook_priorities=priorities,
        do_not_try=sorted(blocked),
        explanation=explanation,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--attempts", type=Path, default=HERE / "attempts.log")
    parser.add_argument("--playbook", type=Path, default=HERE / "playbook.md")
    parser.add_argument("--state", type=Path, default=HERE / "coach_state.json")
    parser.add_argument("--interval", type=int, default=20)
    parser.add_argument("--force", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result = run_coach_if_due(
        attempts_path=args.attempts,
        playbook_path=args.playbook,
        state_path=args.state,
        interval=args.interval,
        force=args.force,
    )
    print(json.dumps(result.to_dict(), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
